### ISSUE TITLE
Could you please tell me your detailed process?

### ISSUE THREAD

**Issue by czy9987** [Ting-505716926/android-yolov4-tflite#1]
I have trained the tflite model, but it is always unsuccessful when transplanting, and the generated APP will always crash.
I am using the code of this project (https://github.com/hunglc007/tensorflow-yolov4-tflite)
The problem I currently encounter is in this place: https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/204
If you have time, I hope you can give me some pointers, thank you!
------------------------------------------------------
**Translation**
我已经训练了tflite模型，但是在进行移植的时候总是无法成功，生成的APP总是会闪退。
我使用的是这个项目的代码（https://github.com/hunglc007/tensorflow-yolov4-tflite）
我目前碰到的问题在这个地方：https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/204
如果您由时间的话希望您能给我一些指点，谢谢！

**Comment by skykongkong8** [comment]
think I have the same issue. Did you solved your problem?

**Comment by czy9987** [comment]
Finally, I found that there was a problem with the model I trained. You need to train yolov4 tiny and follow the conversion steps to convert it into a tflite file

> 想我有同样的问题。你的问题解决了吗？
Finally, I found that there was a problem with the model I trained. You need to train yolov4-tiny and follow the conversion steps to convert it into a tflite file

**Comment by skykongkong8** [comment]
> Finally, I found that there was a problem with the model I trained. You need to train yolov4 tiny and follow the conversion steps to convert it into a tflite file
> 
> > 想我有同样的问题。你的问题解决了吗？
> > Finally, I found that there was a problem with the model I trained. You need to train yolov4-tiny and follow the conversion steps to convert it into a tflite file

Thanks for your immediate response!  
Do you mean that I have to export that data as yolov4-tiny format when I export from roboflow?    
I'm currently following steps from [here](https://blog.roboflow.com/how-to-train-a-custom-mobile-object-detection-model/)
or maybe you can check it in [here](https://colab.research.google.com/drive/1OKzbccsdA40sJ67gqmNyblWuEMCfP5zx?usp=sharing#scrollTo=tqY7VKxyXfd9)    

Is there any guideline that you followed?

**Comment by skykongkong8** [comment]
Actually, I solved my problem. Thank you for your help
